export const NEST_TREASURY_V3_ABI = [
  {
    type: "function",
    name: "createWorkspace",
    stateMutability: "nonpayable",
    inputs: [{ name: "name", type: "string" }],
    outputs: [{ name: "workspaceId", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUserWorkspaces",
    stateMutability: "view",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{
      name: "out",
      type: "tuple[]",
      components: [
        { name: "id", type: "uint256" },
        { name: "name", type: "string" },
        { name: "owner", type: "address" },
        { name: "createdAt", type: "uint64" },
        { name: "approvalThreshold", type: "uint16" },
        { name: "managerCount", type: "uint16" },
        { name: "availableTreasury", type: "uint256" },
        { name: "reservedTreasury", type: "uint256" },
      ],
    }],
  },
  {
    type: "function",
    name: "getWorkspace",
    stateMutability: "view",
    inputs: [{ name: "workspaceId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "id", type: "uint256" },
        { name: "name", type: "string" },
        { name: "owner", type: "address" },
        { name: "createdAt", type: "uint64" },
        { name: "approvalThreshold", type: "uint16" },
        { name: "managerCount", type: "uint16" },
        { name: "availableTreasury", type: "uint256" },
        { name: "reservedTreasury", type: "uint256" },
      ],
    }],
  },
  {
    type: "function",
    name: "deposit",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addMember",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "member", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setManager",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "manager", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setApprovalThreshold",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "threshold", type: "uint16" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "createPaymentProposal",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "memo", type: "string" },
      { name: "expiresAt", type: "uint64" },
    ],
    outputs: [{ name: "proposalId", type: "uint256" }],
  },
  {
    type: "function",
    name: "approveProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "executeProposal",
    stateMutability: "nonpayable",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getWorkspaceProposalIds",
    stateMutability: "view",
    inputs: [{ name: "workspaceId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getProposal",
    stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "id", type: "uint256" },
        { name: "workspaceId", type: "uint256" },
        { name: "proposer", type: "address" },
        { name: "recipient", type: "address" },
        { name: "amount", type: "uint256" },
        { name: "memo", type: "string" },
        { name: "createdAt", type: "uint64" },
        { name: "expiresAt", type: "uint64" },
        { name: "approvals", type: "uint16" },
        { name: "executed", type: "bool" },
        { name: "cancelled", type: "bool" },
      ],
    }],
  },
  {
    type: "function",
    name: "createRecurringPayment",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "intervalSeconds", type: "uint64" },
      { name: "firstExecutionAt", type: "uint64" },
      { name: "executions", type: "uint32" },
      { name: "memo", type: "string" },
    ],
    outputs: [{ name: "recurringId", type: "uint256" }],
  },
  {
    type: "function",
    name: "executeRecurringPayment",
    stateMutability: "nonpayable",
    inputs: [{ name: "recurringId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getWorkspaceRecurringIds",
    stateMutability: "view",
    inputs: [{ name: "workspaceId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getRecurringPayment",
    stateMutability: "view",
    inputs: [{ name: "recurringId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "id", type: "uint256" },
        { name: "workspaceId", type: "uint256" },
        { name: "recipient", type: "address" },
        { name: "amount", type: "uint256" },
        { name: "intervalSeconds", type: "uint64" },
        { name: "nextExecutionAt", type: "uint64" },
        { name: "remainingExecutions", type: "uint32" },
        { name: "memo", type: "string" },
        { name: "active", type: "bool" },
      ],
    }],
  },
  {
    type: "function",
    name: "createMilestone",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "description", type: "string" },
    ],
    outputs: [{ name: "milestoneId", type: "uint256" }],
  },
  {
    type: "function",
    name: "approveMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "milestoneId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "releaseMilestone",
    stateMutability: "nonpayable",
    inputs: [{ name: "milestoneId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "getWorkspaceMilestoneIds",
    stateMutability: "view",
    inputs: [{ name: "workspaceId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256[]" }],
  },
  {
    type: "function",
    name: "getMilestone",
    stateMutability: "view",
    inputs: [{ name: "milestoneId", type: "uint256" }],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "id", type: "uint256" },
        { name: "workspaceId", type: "uint256" },
        { name: "recipient", type: "address" },
        { name: "amount", type: "uint256" },
        { name: "description", type: "string" },
        { name: "createdAt", type: "uint64" },
        { name: "approvals", type: "uint16" },
        { name: "released", type: "bool" },
        { name: "cancelled", type: "bool" },
      ],
    }],
  },
  {
    type: "function",
    name: "setBudgetPolicy",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "spender", type: "address" },
      { name: "limit", type: "uint256" },
      { name: "periodSeconds", type: "uint64" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getBudgetPolicy",
    stateMutability: "view",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "spender", type: "address" },
    ],
    outputs: [{
      name: "",
      type: "tuple",
      components: [
        { name: "active", type: "bool" },
        { name: "periodSeconds", type: "uint64" },
        { name: "periodStartedAt", type: "uint64" },
        { name: "limit", type: "uint256" },
        { name: "spent", type: "uint256" },
      ],
    }],
  },
  {
    type: "function",
    name: "spendFromBudget",
    stateMutability: "nonpayable",
    inputs: [
      { name: "workspaceId", type: "uint256" },
      { name: "recipient", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "memo", type: "string" },
    ],
    outputs: [],
  },
] as const;
