/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppAgentRouteImport } from './routes/app.agent'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppBridgeRouteImport } from './routes/app.bridge'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppLendRouteImport } from './routes/app.lend'
import { Route as AppMembersRouteImport } from './routes/app.members'
import { Route as AppReceiptsRouteImport } from './routes/app.receipts'
import { Route as AppSettleRouteImport } from './routes/app.settle'
import { Route as AppSyndicateRouteImport } from './routes/app.syndicate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBridgeRoute = AppBridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppLendRoute = AppLendRouteImport.update({
  id: '/lend',
  path: '/lend',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettleRoute = AppSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => AppRoute,
} as any)
const AppSyndicateRoute = AppSyndicateRouteImport.update({
  id: '/syndicate',
  path: '/syndicate',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bridge': typeof AppBridgeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/lend': typeof AppLendRoute
  '/app/members': typeof AppMembersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/settle': typeof AppSettleRoute
  '/app/syndicate': typeof AppSyndicateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bridge': typeof AppBridgeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/lend': typeof AppLendRoute
  '/app/members': typeof AppMembersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/settle': typeof AppSettleRoute
  '/app/syndicate': typeof AppSyndicateRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/activity': typeof AppActivityRoute
  '/app/agent': typeof AppAgentRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/bridge': typeof AppBridgeRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/lend': typeof AppLendRoute
  '/app/members': typeof AppMembersRoute
  '/app/receipts': typeof AppReceiptsRoute
  '/app/settle': typeof AppSettleRoute
  '/app/syndicate': typeof AppSyndicateRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/agent'
    | '/app/analytics'
    | '/app/bridge'
    | '/app/expenses'
    | '/app/lend'
    | '/app/members'
    | '/app/receipts'
    | '/app/settle'
    | '/app/syndicate'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity'
    | '/app/agent'
    | '/app/analytics'
    | '/app/bridge'
    | '/app/expenses'
    | '/app/lend'
    | '/app/members'
    | '/app/receipts'
    | '/app/settle'
    | '/app/syndicate'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity'
    | '/app/agent'
    | '/app/analytics'
    | '/app/bridge'
    | '/app/expenses'
    | '/app/lend'
    | '/app/members'
    | '/app/receipts'
    | '/app/settle'
    | '/app/syndicate'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bridge': {
      id: '/app/bridge'
      path: '/bridge'
      fullPath: '/app/bridge'
      preLoaderRoute: typeof AppBridgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lend': {
      id: '/app/lend'
      path: '/lend'
      fullPath: '/app/lend'
      preLoaderRoute: typeof AppLendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts': {
      id: '/app/receipts'
      path: '/receipts'
      fullPath: '/app/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settle': {
      id: '/app/settle'
      path: '/settle'
      fullPath: '/app/settle'
      preLoaderRoute: typeof AppSettleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/syndicate': {
      id: '/app/syndicate'
      path: '/syndicate'
      fullPath: '/app/syndicate'
      preLoaderRoute: typeof AppSyndicateRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAgentRoute: typeof AppAgentRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBridgeRoute: typeof AppBridgeRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppLendRoute: typeof AppLendRoute
  AppMembersRoute: typeof AppMembersRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppSettleRoute: typeof AppSettleRoute
  AppSyndicateRoute: typeof AppSyndicateRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAgentRoute: AppAgentRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBridgeRoute: AppBridgeRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppLendRoute: AppLendRoute,
  AppMembersRoute: AppMembersRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppSettleRoute: AppSettleRoute,
  AppSyndicateRoute: AppSyndicateRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
